name: Sync Labels from Central Config

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: [main, master]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      # This is Step 1. The '-' is critical.
      - name: Checkout central config repo
        uses: actions/checkout@v4
        with:
          repository: ForYouPage-Org/.github
          path: .github-central

      # This is Step 2. The '-' makes it a separate step.
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github-central/labels.yml
          prune: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
