name: 📅 Calendar Sync

on:
  issues:
    types: [opened, edited, milestoned]
  
  # Manual trigger to sync all issues
  workflow_dispatch:

jobs:
  sync-to-calendar:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      
    steps:
      - name: 🔍 Extract Due Date
        id: extract-date
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue) return;
            
            // Look for due dates in various formats
            const title = issue.title || '';
            const body = issue.body || '';
            const milestone = issue.milestone;
            
            let dueDate = null;
            let eventTitle = issue.title;
            
            // Check title for dates like [7/4], [Due: 07/07/2025]
            const titleDateMatch = title.match(/\[(?:Due:\s*)?(\d{1,2}\/\d{1,2}(?:\/\d{2,4})?)\]/);
            if (titleDateMatch) {
              dueDate = titleDateMatch[1];
              eventTitle = title.replace(titleDateMatch[0], '').trim();
            }
            
            // Check milestone due date
            if (!dueDate && milestone?.due_on) {
              dueDate = milestone.due_on;
            }
            
            // Check body for due dates
            if (!dueDate) {
              const bodyDateMatch = body.match(/Due(?:\s+date)?:\s*(\d{1,2}\/\d{1,2}(?:\/\d{2,4})?)/i);
              if (bodyDateMatch) {
                dueDate = bodyDateMatch[1];
              }
            }
            
            if (dueDate) {
              core.setOutput('has_date', 'true');
              core.setOutput('due_date', dueDate);
              core.setOutput('event_title', eventTitle);
              core.setOutput('issue_number', issue.number);
              core.setOutput('issue_url', issue.html_url);
            } else {
              core.setOutput('has_date', 'false');
            }
            
      - name: 📅 Create Calendar Event
        if: steps.extract-date.outputs.has_date == 'true'
        uses: AnandChowdhary/calendar-link@v2
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_private_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          calendar_id: ${{ secrets.GOOGLE_CALENDAR_ID }}
          event_data: |
            {
              "summary": "${{ steps.extract-date.outputs.event_title }} (#${{ steps.extract-date.outputs.issue_number }})",
              "description": "GitHub Issue: ${{ steps.extract-date.outputs.issue_url }}\n\nView and update progress on GitHub.",
              "start": {
                "date": "${{ steps.extract-date.outputs.due_date }}"
              },
              "end": {
                "date": "${{ steps.extract-date.outputs.due_date }}"
              },
              "reminders": {
                "useDefault": false,
                "overrides": [
                  {"method": "popup", "minutes": 1440},
                  {"method": "email", "minutes": 2880}
                ]
              }
            }
            
      - name: 💬 Add Confirmation Comment
        if: steps.extract-date.outputs.has_date == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.extract-date.outputs.issue_number }},
              body: '📅 Calendar event created for due date: ${{ steps.extract-date.outputs.due_date }}'
            });