name: Sync Labels from Central Config
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: [main, master]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        env:
          # This section is crucial. It tells the action where to find the file.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE: https://raw.githubusercontent.com/ForYouPage-Org/.github/main/labels.yml
        with:
          prune: true
