name: Organization Sync

on:
  workflow_dispatch:
    inputs:
      sync_labels:
        description: 'Sync labels to all repositories'
        required: false
        default: 'true'
        type: boolean

jobs:
  sync-organization:
    name: Sync Organization
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Sync Labels
        if: github.event.inputs.sync_labels != 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_ORGANIZATION: ${{ github.repository_owner }}
        run: |
          echo "Starting label sync..."
          node scripts/sync-labels.js