name: 🏷️ Sync Labels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [main, master]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      
    steps:
      - name: 🔄 Checkout Central Config
        uses: actions/checkout@v4
        with:
          repository: ForYouPage-Org/.github
          
      - name: 🏷️ Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          prune: true
          
      - name: 📊 Report Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Labels synced successfully!"
            echo "🏷️ All labels are now in sync with central configuration"
          else
            echo "❌ Label sync failed!"
            echo "Please check the logs for more information"
          fi